"""empty message

Revision ID: 44103ca4ed8a
Revises: 2807edd385a2
Create Date: 2022-04-07 21:51:17.928570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44103ca4ed8a'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('favorites', sa.Integer(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=520),
               nullable=True)
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('user', 'password',
               existing_type=sa.String(length=520),
               type_=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'favorites')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
